// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrcv1jP9meCdkQ_QfmKBSas-Bitjk6nvM',
    appId: '1:201983023095:android:f8c1b8b4b70386e332c0f2',
    messagingSenderId: '201983023095',
    projectId: 'sendnotification-d8a4b',
    databaseURL: 'https://sendnotification-d8a4b.firebaseio.com',
    storageBucket: 'sendnotification-d8a4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvM_TmlUiw60u2_7iRNdmIBx9hdkzyCRg',
    appId: '1:201983023095:ios:703c53424584125632c0f2',
    messagingSenderId: '201983023095',
    projectId: 'sendnotification-d8a4b',
    databaseURL: 'https://sendnotification-d8a4b.firebaseio.com',
    storageBucket: 'sendnotification-d8a4b.appspot.com',
    androidClientId: '201983023095-2ush6a8gg8f2o8ri6kak2k84r4ulj9hm.apps.googleusercontent.com',
    iosClientId: '201983023095-5m055ie2l6617k00i2u2l2bdu3fj958d.apps.googleusercontent.com',
    iosBundleId: 'com.example',
  );
}
